/**
 * Status Enums across domain models in CareConnect
 */

const USER_STATUS = Object.freeze({
  ACTIVE: 'ACTIVE',
  PENDING_VERIFICATION: 'PENDING_VERIFICATION',
  SUSPENDED: 'SUSPENDED',
});

const SERVICE_REQUEST_STATUS = Object.freeze({
  DRAFT: 'DRAFT',
  SUBMITTED: 'SUBMITTED',
  MATCHING: 'MATCHING',
  QUOTED: 'QUOTED',
  BOOKED: 'BOOKED',
  CANCELLED: 'CANCELLED',
  COMPLETED: 'COMPLETED',
});

const QUOTE_STATUS = Object.freeze({
  PENDING: 'PENDING',
  ACCEPTED: 'ACCEPTED',
  REJECTED: 'REJECTED',
  EXPIRED: 'EXPIRED',
});

const BOOKING_STATUS = Object.freeze({
  CONFIRMED: 'CONFIRMED',
  IN_PROGRESS: 'IN_PROGRESS',
  COMPLETED: 'COMPLETED',
  CANCELLED: 'CANCELLED',
  DISPUTED: 'DISPUTED',
});

const JOB_STATUS = Object.freeze({
  SCHEDULED: 'SCHEDULED',
  DISPATCHED: 'DISPATCHED',
  ON_SITE: 'ON_SITE',
  IN_PROGRESS: 'IN_PROGRESS',
  WORK_DONE: 'WORK_DONE',
  INVOICED: 'INVOICED',
  CLOSED: 'CLOSED',
});

const INVOICE_STATUS = Object.freeze({
  ISSUED: 'ISSUED',
  PAID: 'PAID',
  REFUNDED: 'REFUNDED',
  VOID: 'VOID',
});

const DISPUTE_STATUS = Object.freeze({
  OPEN: 'OPEN',
  UNDER_REVIEW: 'UNDER_REVIEW',
  RESOLVED: 'RESOLVED',
  ESCALATED: 'ESCALATED',
  DISMISSED: 'DISMISSED',
});

module.exports = {
  USER_STATUS,
  SERVICE_REQUEST_STATUS,
  QUOTE_STATUS,
  BOOKING_STATUS,
  JOB_STATUS,
  INVOICE_STATUS,
  DISPUTE_STATUS,
};
