/**
 * Centralized Domain Lifecycle Status Enums & State Transition Rules
 * Enforces predictable finite state machine transitions across CareConnect entities.
 */

const USER_STATUS = Object.freeze({
  ACTIVE: 'ACTIVE',
  INACTIVE: 'INACTIVE',
  SUSPENDED: 'SUSPENDED',
  PENDING: 'PENDING',
  // Backward compatibility alias
  PENDING_VERIFICATION: 'PENDING',
});

const SERVICE_REQUEST_STATUS = Object.freeze({
  DRAFT: 'DRAFT',
  SUBMITTED: 'SUBMITTED',
  MATCHING: 'MATCHING',
  QUOTING: 'QUOTING',
  PROVIDER_SELECTED: 'PROVIDER_SELECTED',
  BOOKED: 'BOOKED',
  IN_PROGRESS: 'IN_PROGRESS',
  COMPLETED: 'COMPLETED',
  CANCELLED: 'CANCELLED',
  DISPUTED: 'DISPUTED',
});

const QUOTE_STATUS = Object.freeze({
  SUBMITTED: 'SUBMITTED',
  VIEWED: 'VIEWED',
  ACCEPTED: 'ACCEPTED',
  REJECTED: 'REJECTED',
  EXPIRED: 'EXPIRED',
  WITHDRAWN: 'WITHDRAWN',
  // Backward compatibility alias
  PENDING: 'SUBMITTED',
});

const BOOKING_STATUS = Object.freeze({
  PENDING: 'PENDING',
  CONFIRMED: 'CONFIRMED',
  IN_PROGRESS: 'IN_PROGRESS',
  COMPLETED: 'COMPLETED',
  CANCELLED: 'CANCELLED',
  DISPUTED: 'DISPUTED',
});

const JOB_STATUS = Object.freeze({
  ASSIGNED: 'ASSIGNED',
  ON_THE_WAY: 'ON_THE_WAY',
  CHECKED_IN: 'CHECKED_IN',
  IN_PROGRESS: 'IN_PROGRESS',
  COMPLETED: 'COMPLETED',
  CANCELLED: 'CANCELLED',
});

const INVOICE_STATUS = Object.freeze({
  DRAFT: 'DRAFT',
  ISSUED: 'ISSUED',
  PAID: 'PAID',
  REFUNDED: 'REFUNDED',
  VOID: 'VOID',
});

// Valid invoice state transitions
const VALID_INVOICE_TRANSITIONS = Object.freeze({
  [INVOICE_STATUS.DRAFT]: [INVOICE_STATUS.ISSUED],
  [INVOICE_STATUS.ISSUED]: [INVOICE_STATUS.PAID, INVOICE_STATUS.VOID],
  [INVOICE_STATUS.PAID]: [INVOICE_STATUS.REFUNDED],
  [INVOICE_STATUS.VOID]: [],
  [INVOICE_STATUS.REFUNDED]: [],
});

const DISPUTE_STATUS = Object.freeze({
  OPEN: 'OPEN',
  UNDER_REVIEW: 'UNDER_REVIEW',
  RESOLVED: 'RESOLVED',
  REJECTED: 'REJECTED',
  CANCELLED: 'CANCELLED',
});

const VALID_DISPUTE_TRANSITIONS = Object.freeze({
  [DISPUTE_STATUS.OPEN]: [DISPUTE_STATUS.UNDER_REVIEW, DISPUTE_STATUS.CANCELLED],
  [DISPUTE_STATUS.UNDER_REVIEW]: [DISPUTE_STATUS.RESOLVED, DISPUTE_STATUS.REJECTED],
  [DISPUTE_STATUS.RESOLVED]: [],
  [DISPUTE_STATUS.REJECTED]: [],
  [DISPUTE_STATUS.CANCELLED]: [],
});

/**
 * State Transition Allowed Mappings
 * Maps current status to array of valid subsequent target statuses.
 */
const VALID_REQUEST_TRANSITIONS = Object.freeze({
  [SERVICE_REQUEST_STATUS.DRAFT]: [SERVICE_REQUEST_STATUS.SUBMITTED, SERVICE_REQUEST_STATUS.CANCELLED],
  [SERVICE_REQUEST_STATUS.SUBMITTED]: [SERVICE_REQUEST_STATUS.MATCHING, SERVICE_REQUEST_STATUS.CANCELLED],
  [SERVICE_REQUEST_STATUS.MATCHING]: [SERVICE_REQUEST_STATUS.QUOTING, SERVICE_REQUEST_STATUS.CANCELLED],
  [SERVICE_REQUEST_STATUS.QUOTING]: [
    SERVICE_REQUEST_STATUS.PROVIDER_SELECTED,
    SERVICE_REQUEST_STATUS.BOOKED,
    SERVICE_REQUEST_STATUS.CANCELLED,
  ],
  [SERVICE_REQUEST_STATUS.PROVIDER_SELECTED]: [SERVICE_REQUEST_STATUS.BOOKED, SERVICE_REQUEST_STATUS.CANCELLED],
  [SERVICE_REQUEST_STATUS.BOOKED]: [SERVICE_REQUEST_STATUS.IN_PROGRESS, SERVICE_REQUEST_STATUS.CANCELLED],
  [SERVICE_REQUEST_STATUS.IN_PROGRESS]: [SERVICE_REQUEST_STATUS.COMPLETED, SERVICE_REQUEST_STATUS.DISPUTED],
  [SERVICE_REQUEST_STATUS.COMPLETED]: [SERVICE_REQUEST_STATUS.DISPUTED],
  [SERVICE_REQUEST_STATUS.CANCELLED]: [],
  [SERVICE_REQUEST_STATUS.DISPUTED]: [SERVICE_REQUEST_STATUS.COMPLETED, SERVICE_REQUEST_STATUS.CANCELLED],
});

const DAYS_OF_WEEK = Object.freeze({
  MONDAY: 'MONDAY',
  TUESDAY: 'TUESDAY',
  WEDNESDAY: 'WEDNESDAY',
  THURSDAY: 'THURSDAY',
  FRIDAY: 'FRIDAY',
  SATURDAY: 'SATURDAY',
  SUNDAY: 'SUNDAY',
});

const VALID_QUOTE_TRANSITIONS = Object.freeze({
  [QUOTE_STATUS.SUBMITTED]: [
    QUOTE_STATUS.VIEWED,
    QUOTE_STATUS.ACCEPTED,
    QUOTE_STATUS.REJECTED,
    QUOTE_STATUS.WITHDRAWN,
    QUOTE_STATUS.EXPIRED,
  ],
  [QUOTE_STATUS.VIEWED]: [
    QUOTE_STATUS.ACCEPTED,
    QUOTE_STATUS.REJECTED,
    QUOTE_STATUS.WITHDRAWN,
    QUOTE_STATUS.EXPIRED,
  ],
  [QUOTE_STATUS.ACCEPTED]: [],
  [QUOTE_STATUS.REJECTED]: [],
  [QUOTE_STATUS.EXPIRED]: [],
  [QUOTE_STATUS.WITHDRAWN]: [],
});

const VALID_BOOKING_TRANSITIONS = Object.freeze({
  [BOOKING_STATUS.PENDING]: [BOOKING_STATUS.CONFIRMED, BOOKING_STATUS.CANCELLED],
  [BOOKING_STATUS.CONFIRMED]: [BOOKING_STATUS.IN_PROGRESS, BOOKING_STATUS.CANCELLED],
  [BOOKING_STATUS.IN_PROGRESS]: [BOOKING_STATUS.COMPLETED, BOOKING_STATUS.DISPUTED, BOOKING_STATUS.CANCELLED],
  [BOOKING_STATUS.COMPLETED]: [BOOKING_STATUS.DISPUTED],
  [BOOKING_STATUS.CANCELLED]: [],
  [BOOKING_STATUS.DISPUTED]: [BOOKING_STATUS.COMPLETED, BOOKING_STATUS.CANCELLED],
});

const VALID_JOB_TRANSITIONS = Object.freeze({
  [JOB_STATUS.ASSIGNED]: [JOB_STATUS.ON_THE_WAY, JOB_STATUS.CANCELLED],
  [JOB_STATUS.ON_THE_WAY]: [JOB_STATUS.CHECKED_IN, JOB_STATUS.CANCELLED],
  [JOB_STATUS.CHECKED_IN]: [JOB_STATUS.IN_PROGRESS, JOB_STATUS.CANCELLED],
  [JOB_STATUS.IN_PROGRESS]: [JOB_STATUS.COMPLETED, JOB_STATUS.CANCELLED],
  [JOB_STATUS.COMPLETED]: [],
  [JOB_STATUS.CANCELLED]: [],
});

const PROVIDER_VERIFICATION_STATUS = Object.freeze({
  PENDING: 'PENDING',
  UNDER_REVIEW: 'UNDER_REVIEW',
  APPROVED: 'APPROVED',
  REJECTED: 'REJECTED',
  SUSPENDED: 'SUSPENDED',
});

const VALID_PROVIDER_VERIFICATION_TRANSITIONS = Object.freeze({
  [PROVIDER_VERIFICATION_STATUS.PENDING]: [
    PROVIDER_VERIFICATION_STATUS.UNDER_REVIEW,
    PROVIDER_VERIFICATION_STATUS.APPROVED,
    PROVIDER_VERIFICATION_STATUS.REJECTED,
  ],
  [PROVIDER_VERIFICATION_STATUS.UNDER_REVIEW]: [
    PROVIDER_VERIFICATION_STATUS.APPROVED,
    PROVIDER_VERIFICATION_STATUS.REJECTED,
    PROVIDER_VERIFICATION_STATUS.PENDING,
  ],
  [PROVIDER_VERIFICATION_STATUS.APPROVED]: [
    PROVIDER_VERIFICATION_STATUS.SUSPENDED,
    PROVIDER_VERIFICATION_STATUS.UNDER_REVIEW,
  ],
  [PROVIDER_VERIFICATION_STATUS.REJECTED]: [
    PROVIDER_VERIFICATION_STATUS.PENDING,
    PROVIDER_VERIFICATION_STATUS.UNDER_REVIEW,
  ],
  [PROVIDER_VERIFICATION_STATUS.SUSPENDED]: [
    PROVIDER_VERIFICATION_STATUS.UNDER_REVIEW,
    PROVIDER_VERIFICATION_STATUS.APPROVED,
  ],
});

const SUPPORT_TICKET_STATUS = Object.freeze({
  OPEN: 'OPEN',
  IN_PROGRESS: 'IN_PROGRESS',
  WAITING_FOR_CUSTOMER: 'WAITING_FOR_CUSTOMER',
  WAITING_FOR_PROVIDER: 'WAITING_FOR_PROVIDER',
  RESOLVED: 'RESOLVED',
  CLOSED: 'CLOSED',
});

const VALID_SUPPORT_TICKET_TRANSITIONS = Object.freeze({
  [SUPPORT_TICKET_STATUS.OPEN]: [
    SUPPORT_TICKET_STATUS.IN_PROGRESS,
    SUPPORT_TICKET_STATUS.WAITING_FOR_CUSTOMER,
    SUPPORT_TICKET_STATUS.WAITING_FOR_PROVIDER,
    SUPPORT_TICKET_STATUS.RESOLVED,
    SUPPORT_TICKET_STATUS.CLOSED,
  ],
  [SUPPORT_TICKET_STATUS.IN_PROGRESS]: [
    SUPPORT_TICKET_STATUS.WAITING_FOR_CUSTOMER,
    SUPPORT_TICKET_STATUS.WAITING_FOR_PROVIDER,
    SUPPORT_TICKET_STATUS.RESOLVED,
    SUPPORT_TICKET_STATUS.CLOSED,
  ],
  [SUPPORT_TICKET_STATUS.WAITING_FOR_CUSTOMER]: [
    SUPPORT_TICKET_STATUS.IN_PROGRESS,
    SUPPORT_TICKET_STATUS.RESOLVED,
    SUPPORT_TICKET_STATUS.CLOSED,
  ],
  [SUPPORT_TICKET_STATUS.WAITING_FOR_PROVIDER]: [
    SUPPORT_TICKET_STATUS.IN_PROGRESS,
    SUPPORT_TICKET_STATUS.RESOLVED,
    SUPPORT_TICKET_STATUS.CLOSED,
  ],
  [SUPPORT_TICKET_STATUS.RESOLVED]: [
    SUPPORT_TICKET_STATUS.IN_PROGRESS,
    SUPPORT_TICKET_STATUS.CLOSED,
  ],
  [SUPPORT_TICKET_STATUS.CLOSED]: [],
});

const SUPPORT_TICKET_PRIORITY = Object.freeze({
  LOW: 'LOW',
  MEDIUM: 'MEDIUM',
  HIGH: 'HIGH',
  URGENT: 'URGENT',
});

const SUPPORT_TICKET_CATEGORY = Object.freeze({
  BOOKING: 'BOOKING',
  PAYMENT: 'PAYMENT',
  JOB: 'JOB',
  PROVIDER: 'PROVIDER',
  CUSTOMER: 'CUSTOMER',
  DISPUTE: 'DISPUTE',
  ACCOUNT: 'ACCOUNT',
  TECHNICAL: 'TECHNICAL',
  OTHER: 'OTHER',
});

const NOTIFICATION_TYPE = Object.freeze({
  ACCOUNT_REGISTERED: 'ACCOUNT_REGISTERED',
  ACCOUNT_STATUS_CHANGED: 'ACCOUNT_STATUS_CHANGED',
  BOOKING_CREATED: 'BOOKING_CREATED',
  BOOKING_CONFIRMED: 'BOOKING_CONFIRMED',
  BOOKING_CANCELLED: 'BOOKING_CANCELLED',
  BOOKING_RESCHEDULED: 'BOOKING_RESCHEDULED',
  JOB_ASSIGNED: 'JOB_ASSIGNED',
  JOB_ON_THE_WAY: 'JOB_ON_THE_WAY',
  JOB_CHECKED_IN: 'JOB_CHECKED_IN',
  JOB_IN_PROGRESS: 'JOB_IN_PROGRESS',
  JOB_COMPLETED: 'JOB_COMPLETED',
  JOB_CONFIRMED: 'JOB_CONFIRMED',
  INVOICE_GENERATED: 'INVOICE_GENERATED',
  INVOICE_PAID: 'INVOICE_PAID',
  INVOICE_STATUS_CHANGED: 'INVOICE_STATUS_CHANGED',
  REVIEW_RECEIVED: 'REVIEW_RECEIVED',
  DISPUTE_CREATED: 'DISPUTE_CREATED',
  DISPUTE_UNDER_REVIEW: 'DISPUTE_UNDER_REVIEW',
  DISPUTE_RESOLVED: 'DISPUTE_RESOLVED',
  DISPUTE_REJECTED: 'DISPUTE_REJECTED',
  DISPUTE_CANCELLED: 'DISPUTE_CANCELLED',
  SUPPORT_TICKET_CREATED: 'SUPPORT_TICKET_CREATED',
  SUPPORT_TICKET_ASSIGNED: 'SUPPORT_TICKET_ASSIGNED',
  SUPPORT_TICKET_STATUS_CHANGED: 'SUPPORT_TICKET_STATUS_CHANGED',
  SUPPORT_TICKET_MESSAGE: 'SUPPORT_TICKET_MESSAGE',
  SYSTEM: 'SYSTEM',
  OTHER: 'OTHER',
});

/**
 * Validates whether a state transition is permitted
 * @param {Object} transitionMap
 * @param {string} fromStatus
 * @param {string} toStatus
 * @returns {boolean}
 */
const isValidTransition = (transitionMap, fromStatus, toStatus) => {
  if (fromStatus === toStatus) return true;
  const allowed = transitionMap[fromStatus];
  return Boolean(allowed && allowed.includes(toStatus));
};

module.exports = {
  USER_STATUS,
  SERVICE_REQUEST_STATUS,
  QUOTE_STATUS,
  BOOKING_STATUS,
  JOB_STATUS,
  INVOICE_STATUS,
  DISPUTE_STATUS,
  SUPPORT_TICKET_STATUS,
  SUPPORT_TICKET_PRIORITY,
  SUPPORT_TICKET_CATEGORY,
  NOTIFICATION_TYPE,
  PROVIDER_VERIFICATION_STATUS,
  DAYS_OF_WEEK,
  VALID_REQUEST_TRANSITIONS,
  VALID_QUOTE_TRANSITIONS,
  VALID_BOOKING_TRANSITIONS,
  VALID_JOB_TRANSITIONS,
  VALID_INVOICE_TRANSITIONS,
  VALID_DISPUTE_TRANSITIONS,
  VALID_SUPPORT_TICKET_TRANSITIONS,
  VALID_PROVIDER_VERIFICATION_TRANSITIONS,
  isValidTransition,
};
